### ISSUE TITLE
[py3] You shall not pass! - issue when accessing admin area

### ISSUE THREAD

**Issue by jessecooper** [buildbot/buildbot_travis#64]
I get the following message when trying to access the admin area when running in a virtualenv:

> You shall not pass! - issue when accessing admin area
> need admin rights to access administration panels

Not sure if I am missing something in my configuration or if something else might be going on.

**Comment by tardyp** [comment]
It is because you configured an authentication plugin before. You can look at the cfg.yml to fix it manually before you can use the UI again

**Comment by meritozh** [comment]
@tardyp Please help me. How I modify cfg.yml then I can use GitHub auth to auth bbtravis or manually register email as account?

**Comment by meritozh** [comment]
Or just use `UserPasswordAuth`

**Comment by tardyp** [comment]
can you show your cfg.yml (the auth part?)

**Comment by meritozh** [comment]
```yml
auth
      - type: Custom
      - customcode: "from buildbot.plugins import *\nauth = util.UserPasswordAuth({\"homer\": \"doh!\"})"
```

Just use username and password to login. But this accout has no admin right. Am I must write 
more python code in yml to make role as admin?

By the way, how to set it to use GitHub Enterprise auth to login?
