### ISSUE TITLE
Commands are over-escaped on Windows workers and result in failures

### ISSUE THREAD

**Issue by vdsbenoit** [buildbot/buildbot_travis#98]
I think the commands are over-escaped on Windows workers.  
This exceed of escaping gets problematic when a command is split over several lines with the *Folded Block Scalar* `>` (YAML specification).

Here is a example:
````yaml
script:
  - title: induce buildbot-travis cmd issue
    shell: cmd
    cmd: >
      pip install
      numpy
      scipy
````

Here is the log of the execution of the here-above step on a Windows Docker worker :

````shell
0  cmd -c ^"pip install numpy scipy
1  ^"
2  in dir c:\worker\myworker-job\build (timeout 1200 secs)
3  watching logfiles {}
4  argv: [b'cmd', b'-c', b'pip install numpy scipy\n']
5  environment:
6   ALLUSERSPROFILE=C:\ProgramData

...

68 '"' is not recognized as an internal or external command,
69 operable program or batch file.
70 program finished with exit code 1
````

A new line character ends the command written with a *Folded Block Scalar*. This should not be a problem as it would only execute an empty command after the actual command. However, it raises an error as the `"` character is escaped.

**Comment by vdsbenoit** [comment]
The issue blocks also the use of *Literal Block Scalar* `|` : 

````yaml
- title: induce buildbot-travis cmd issue
  shell: cmd
  cmd: |
    conda create -n foo -y
    conda activate foo
    python --version
```` 

The 3 commands will be interpreted as one : 

````shell
0  cmd -c ^"conda create -n foo -y
1  conda activate foo
2  python --version
3  ^"
````

**Comment by seankelly** [comment]
Is the issue the newline at the end of the string? There's a YAML option to strip that, add a `-`. Works for `|` and `>`.

```- title: induce buildbot-travis cmd issue
  shell: cmd
  cmd: |-
    conda create -n foo -y
    conda activate foo
    python --version
```

```[{'cmd': 'conda create -n foo -y\nconda activate foo\npython --version',
  'shell': 'cmd',
  'title': 'induce buildbot-travis cmd issue'}]
```

**Comment by vdsbenoit** [comment]
I actually found the issue and fixed it locally. The problem is in 3 parts:

1. buildbot-travis does not correctly handle YAML scalars
2. buildbot ShellCommand command must be a single string (not a list) not to be escaped
3. if no shells are given, bash will be used as default which is wrong with a Windows worker

I will open a pull request soon.

**Comment by vdsbenoit** [comment]
@seankelly : using a ``-`` will remove the extra line break. It solves my first issue but creates another one. It looks like commands will run independently. 
Therefore, the result of this: 
````yml 
- title: activate foo
  shell: cmd
  cmd: |-
    conda create -n foo -y python=2.7
    conda activate foo
    python --version
````
will be 
````shell
0 cmd -c ^"conda create -n foo -y python=2.7
1 conda activate foo
2 python --version^"

[...]

71 Could not find conda environment: foo
72 You can list all discoverable environments with `conda info --envs`.
````

I also tried this: 
````yml 
  - title: create cond env
    shell: cmd
    cmd: conda create -n foo -y python=2.7

  - title: activate foo
    shell: cmd
    cmd: |-
          conda activate foo
          python --version
          conda info --envs
````
and the result was:
````shell
0 cmd -c ^"conda activate foo
1 python --version
2 conda info --envs^"

[...]

71 [...]>Python 3.7.0
72 # conda environments:
73 #
74 base                  *  C:\tools\Miniconda3
75 foo                      C:\tools\Miniconda3\envs\foo
76                          c:\tools\Miniconda3
````


My solution to this issue is to replace line breaks with ``&&`` characters. I tested it locally and it works marvelously. I will share it soon
